// @ts-check
import { afterEach, beforeEach, describe, expect, test, vi } from "vitest";

import {
  NUDGE_DEFS,
  _isNudgeDismissed,
  _nudgeDismissed,
  _nudgeKey,
  dismissNudge,
  removeNudge,
  showNudge,
} from "../bpp/web/static/js/modules/nudges.mjs";
import { _setDbSettings, getSetting } from "../bpp/web/static/js/modules/settings-client.mjs";

/** @type {Record<string, string>} */
let lsStore;

beforeEach(() => {
  vi.useFakeTimers();
  document.body.innerHTML = `<div id="nudge-container"></div>`;
  // Reset settings cache + in-memory dismissal memo between tests.
  _setDbSettings({});
  _nudgeDismissed.clear();
  /** @type {any} */ (window)._isTourActive = () => false;

  // dismissNudge is referenced from inline `onclick=""` HTML strings
  // generated by showNudge, so it has to be reachable as a global at
  // click time. index.html does this via Object.assign(window, nudges)
  // — mirror it here.
  /** @type {any} */ (window).dismissNudge = dismissNudge;

  // settings-client.saveSetting fires apiFetch in the background;
  // give it a stub so tests don't blow up on the network call.
  vi.stubGlobal(
    "fetch",
    vi.fn(
      async () =>
        new Response(JSON.stringify({}), {
          status: 200,
          headers: { "content-type": "application/json" },
        })
    )
  );

  lsStore = {};
  vi.stubGlobal("localStorage", {
    getItem: (/** @type {string} */ k) => (k in lsStore ? lsStore[k] : null),
    setItem: (/** @type {string} */ k, /** @type {unknown} */ v) => {
      lsStore[k] = String(v);
    },
    removeItem: (/** @type {string} */ k) => {
      delete lsStore[k];
    },
    clear: () => {
      for (const k of Object.keys(lsStore)) delete lsStore[k];
    },
  });

  // jsdom defines requestAnimationFrame, but we want it to fire
  // synchronously so the .nudge-visible class is observable in
  // assertions without an extra await.
  vi.stubGlobal(
    "requestAnimationFrame",
    /** @param {(t: number) => void} cb */ (cb) => {
      cb(0);
      return 0;
    }
  );
});

afterEach(() => {
  vi.useRealTimers();
  vi.unstubAllGlobals();
  document.body.innerHTML = "";
  _nudgeDismissed.clear();
  _setDbSettings({});
  delete (/** @type {any} */ (window)._isTourActive);
  delete (/** @type {any} */ (window).dismissNudge);
});

const container = () => /** @type {HTMLElement} */ (document.getElementById("nudge-container"));
const banner = (/** @type {string} */ id) =>
  /** @type {HTMLElement | null} */ (document.getElementById("nudge-" + id));

describe("_nudgeKey", () => {
  test("namespaces keys under nudge_<id>", () => {
    expect(_nudgeKey("foo")).toBe("nudge_foo");
    expect(_nudgeKey("analyze_photos")).toBe("nudge_analyze_photos");
  });
});

describe("NUDGE_DEFS", () => {
  test("ships the three known nudge definitions", () => {
    expect(Object.keys(NUDGE_DEFS).sort()).toEqual([
      "analyze_photos",
      "export_ready",
      "pick_people",
    ]);
    for (const def of Object.values(NUDGE_DEFS)) {
      expect(typeof def.message).toBe("string");
    }
  });
});

describe("_isNudgeDismissed", () => {
  test("returns false for a fresh nudge", () => {
    expect(_isNudgeDismissed("analyze_photos")).toBe(false);
  });

  test("returns true when the in-memory memo holds the id", () => {
    _nudgeDismissed.add("pick_people");
    expect(_isNudgeDismissed("pick_people")).toBe(true);
  });

  test("returns true when DB settings persisted the dismissal", () => {
    _setDbSettings({ nudge_export_ready: "dismissed" });
    expect(_isNudgeDismissed("export_ready")).toBe(true);
  });

  test('any value other than "dismissed" in settings is ignored', () => {
    _setDbSettings({ nudge_analyze_photos: "shown" });
    expect(_isNudgeDismissed("analyze_photos")).toBe(false);
  });
});

describe("dismissNudge", () => {
  test("memos the id, persists to settings, animates the banner out", () => {
    showNudge("analyze_photos", "nudge-container");
    expect(banner("analyze_photos")).not.toBeNull();

    dismissNudge("analyze_photos");

    expect(_nudgeDismissed.has("analyze_photos")).toBe(true);
    expect(getSetting("nudge_analyze_photos", null)).toBe("dismissed");

    const el = banner("analyze_photos");
    expect(el?.classList.contains("nudge-hiding")).toBe(true);
    // Removal is timer-driven — fast-forward 300ms.
    vi.advanceTimersByTime(300);
    expect(banner("analyze_photos")).toBeNull();
  });

  test("no-op on the DOM when the banner isn't mounted (still memoizes)", () => {
    dismissNudge("pick_people");
    expect(_nudgeDismissed.has("pick_people")).toBe(true);
    // No banner was ever rendered — no element to remove, no throw.
    expect(banner("pick_people")).toBeNull();
  });
});

describe("showNudge", () => {
  test("renders message + action + close button into the container", () => {
    showNudge("analyze_photos", "nudge-container");
    const el = banner("analyze_photos");
    expect(el).not.toBeNull();
    expect(el?.getAttribute("role")).toBe("status");
    expect(el?.querySelector(".nudge-msg")?.innerHTML).toContain("imported");
    expect(el?.querySelector(".nudge-action")?.textContent).toBe("Analyze Now");
    expect(el?.querySelector(".nudge-close")).not.toBeNull();
    // requestAnimationFrame was stubbed to fire synchronously, so the
    // entrance class should already be applied.
    expect(el?.classList.contains("nudge-visible")).toBe(true);
  });

  test("rendered close button uses data-action dispatcher", () => {
    // The close button now uses data-action + data-arg0 instead of inline
    // onclick. Verify the dispatcher attributes are correctly set.
    showNudge("analyze_photos", "nudge-container");
    const closeBtn = /** @type {HTMLButtonElement} */ (
      banner("analyze_photos")?.querySelector(".nudge-close")
    );
    expect(closeBtn.getAttribute("data-action")).toBe("dismissNudge");
    expect(closeBtn.getAttribute("data-arg0")).toBe("analyze_photos");

    // Simulate what the inline handler does at click time.
    dismissNudge("analyze_photos");
    expect(_nudgeDismissed.has("analyze_photos")).toBe(true);
    vi.advanceTimersByTime(300);
    expect(banner("analyze_photos")).toBeNull();
  });

  test("no-op when the nudge is already dismissed in memo", () => {
    _nudgeDismissed.add("analyze_photos");
    showNudge("analyze_photos", "nudge-container");
    expect(banner("analyze_photos")).toBeNull();
  });

  test("no-op when DB settings say the nudge was dismissed", () => {
    _setDbSettings({ nudge_pick_people: "dismissed" });
    showNudge("pick_people", "nudge-container");
    expect(banner("pick_people")).toBeNull();
  });

  test("no-op while a product tour is running", () => {
    /** @type {any} */ (window)._isTourActive = () => true;
    showNudge("analyze_photos", "nudge-container");
    expect(banner("analyze_photos")).toBeNull();
  });

  test("double-show is idempotent — second call doesn't append a duplicate", () => {
    showNudge("export_ready", "nudge-container");
    showNudge("export_ready", "nudge-container");
    expect(container().querySelectorAll("#nudge-export_ready").length).toBe(1);
  });

  test("unknown id is a silent no-op", () => {
    showNudge("does_not_exist", "nudge-container");
    expect(container().children.length).toBe(0);
  });

  test("missing container is a silent no-op (fail-safe)", () => {
    document.body.innerHTML = "";
    expect(() => showNudge("analyze_photos", "missing")).not.toThrow();
  });
});

describe("removeNudge", () => {
  test("removes the banner from the DOM without persisting dismissal", () => {
    showNudge("export_ready", "nudge-container");
    expect(banner("export_ready")).not.toBeNull();

    removeNudge("export_ready");

    expect(banner("export_ready")).toBeNull();
    // Crucially, no dismissal was persisted — the nudge can re-appear later.
    expect(_nudgeDismissed.has("export_ready")).toBe(false);
    expect(getSetting("nudge_export_ready", null)).toBeNull();
  });

  test("no-op when the banner isn't mounted", () => {
    expect(() => removeNudge("not_mounted")).not.toThrow();
  });
});
